### ISSUE TITLE
Docker compose error

### ISSUE THREAD

**Issue by cryptorevizor** [saeed349/Microservices-Based-Algorithmic-Trading-System#3]
Docker version 19.03.8, build afacb8b

 After command `docker-compose -f "docker-compose.yml" up -d --build` I got this error:

`WARNING: The MAPBOX_API_KEY variable is not set. Defaulting to a blank string.
Creating network "microservices-based-algorithmic-trading-system_default" with the default driver
Creating volume "pg_data" with default driver
Creating volume "pg_data_airflow" with default driver
Creating volume "redis" with default driver
Building minio-image
Traceback (most recent call last):
  File "site-packages\docker\credentials\store.py", line 80, in _execute
  File "subprocess.py", line 395, in check_output
  File "subprocess.py", line 487, in run
subprocess.CalledProcessError: Command '['C:\\Program Files\\Docker\\Docker\\resources\\bin\\docker-credential-desktop.EXE', 'list']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 72, in main
  File "compose\cli\main.py", line 128, in perform_command
  File "compose\cli\main.py", line 1077, in up
  File "compose\cli\main.py", line 1073, in up
  File "compose\project.py", line 548, in up
  File "compose\service.py", line 351, in ensure_image_exists
  File "compose\service.py", line 1106, in build
  File "site-packages\docker\api\build.py", line 261, in build
  File "site-packages\docker\api\build.py", line 308, in _set_auth_headers
  File "site-packages\docker\auth.py", line 302, in get_all_credentials
  File "site-packages\docker\credentials\store.py", line 71, in list
  File "site-packages\docker\credentials\store.py", line 93, in _execute
docker.credentials.errors.StoreError: Credentials store docker-credential-desktop exited with "error listing credentials - err: exec: "docker-credential-wincred.exe": executable file not found in %PATH%, out: ``".
[4468] Failed to execute script docker-compose`

WD=/C/Users/****/Desktop/Microservices-Based-Algorithmic-Trading-System/Storage

Windows 10

**Comment by cryptorevizor** [comment]
Update:

I deleted this line from ~/.docker/config.json
`"credsStore": "desktop"`

Now it's working for me. 

After that i got the second error:
`ERROR: Service 'minio-image' failed to build: image operating system "linux" cannot be used on this platform`

**Comment by saeed349** [comment]
I guess Minio container isnt able to map the storage, are all other containers up and running and are they are mapped to the correct storage ?

**Comment by cryptorevizor** [comment]
Gracies:) I solved this just run `docker-compose up -d --build`. Sorry for stupid questions, but I work with docker first time.

Also, if you try do this in Windows 10, it's not important to install Visual studio. You can just install Docker and use PowerShall console.
Also, check twice if Hyper-V and visialisation in Bios are enabled.
