### ISSUE TITLE
Got error during  starter_script.bat execution

### ISSUE THREAD

**Issue by cryptorevizor** [saeed349/Microservices-Based-Algorithmic-Trading-System#4]
After building docker i tried start the script "starter_script.bat" and got this error. It looks like I have a problem with secmaster_db_symbol_loader.py. 

How can I solve this?

```

PS C:\Users\***\desktop\Microservices-Based-Algorithmic-Trading-System> .\starter_script.bat

C:\Users\***\desktop\Microservices-Based-Algorithmic-Trading-System>echo "scripts on jupyter notebook"
"scripts on jupyter notebook"

C:\Users\***\desktop\Microservices-Based-Algorithmic-Trading-System>docker exec -it jupyter-image /bin/sh -c "python /home/jovyan/work/q_pack/db_pack/schema/secmaster_db_schema_builder.py"
Database does not exist.
Creating new database.
Database exists.
Building tables.
Building tables.
Building tables.
Building tables.
Building tables.

C:\Users\***\desktop\Microservices-Based-Algorithmic-Trading-System>docker exec -it jupyter-image /bin/sh -c "python /home/jovyan/work/q_pack/db_pack/schema/secmaster_db_symbol_loader.py"
Traceback (most recent call last):
  File "/home/jovyan/work/q_pack/db_pack/schema/secmaster_db_symbol_loader.py", line 131, in <module>
    main()
  File "/home/jovyan/work/q_pack/db_pack/schema/secmaster_db_symbol_loader.py", line 118, in main
    symbols = parse_wiki_forex()
  File "/home/jovyan/work/q_pack/db_pack/schema/secmaster_db_symbol_loader.py", line 38, in parse_wiki_forex
    rv = client.request(r)
  File "/opt/conda/lib/python3.7/site-packages/oandapyV20/oandapyV20.py", line 306, in request
    request_args, headers=headers)
  File "/opt/conda/lib/python3.7/site-packages/oandapyV20/oandapyV20.py", line 243, in __request
    response.content.decode('utf-8'))
oandapyV20.exceptions.V20Error: {"errorMessage":"Insufficient authorization to perform request."}

C:\Users\***\desktop\Microservices-Based-Algorithmic-Trading-System>docker exec -it jupyter-image /bin/sh -c "python /home/jovyan/work/q_pack/db_pack/schema/risk_db_schema_builder.py"
Database does not exist.
Creating new database.
Database exists.
Building tables.
Building tables.
Building tables.
Building tables.

C:\Users\***\desktop\Microservices-Based-Algorithmic-Trading-System>echo "..."
"..."
```

**Comment by cryptorevizor** [comment]
Update:

Please add to readme page important information for new users, they should do next:
1. Create demo or real account in Oanda
2. Oanda doesn't give public API
3. New users should generate API key
4. New users should know his ID
5. Copy this (3 and 4) to YOUR_DIRECTORY\Storage\q_pack\q_credentials\oanda_cred.py
acc_id_practice = "your id"
token_practice = "your token"

After this my problem was solved.

**Comment by saeed349** [comment]
Hi @cryptorevizor a new release with a few architectural changes is coming in the next few weeks, I will update the readme in that release.
