### ISSUE TITLE
secmaster_db_symbol_loader fails with insufficient auth

### ISSUE THREAD

**Issue by hallicarnassus** [saeed349/Microservices-Based-Algorithmic-Trading-System#6]
Built using Ubuntu 16.04.7 LTS
Docker version 20.10.1, build 831ebea
docker-compose version 1.27.4, build 40524192

Traceback (most recent call last):
  File "/home/jovyan/work/q_pack/db_pack/schema/secmaster_db_symbol_loader.py", line 131, in <module>
    main()
  File "/home/jovyan/work/q_pack/db_pack/schema/secmaster_db_symbol_loader.py", line 118, in main
    symbols = parse_wiki_forex()
  File "/home/jovyan/work/q_pack/db_pack/schema/secmaster_db_symbol_loader.py", line 38, in parse_wiki_forex
    rv = client.request(r)
  File "/opt/conda/lib/python3.8/site-packages/oandapyV20/oandapyV20.py", line 305, in request
    response = self.__request(method, url,
  File "/opt/conda/lib/python3.8/site-packages/oandapyV20/oandapyV20.py", line 242, in __request
    raise V20Error(response.status_code,
oandapyV20.exceptions.V20Error: {"errorMessage":"Insufficient authorization to perform request."}

**Comment by drbothen** [comment]
This is related to the oanda api creds not being updated.

You need to supply your oanda creds to this file: https://github.com/saeed349/Microservices-Based-Algorithmic-Trading-System/blob/master/Storage/q_pack/q_credentials/oanda_cred.py

**Comment by himanshueip** [comment]
I dont have onda account and they have close account opening for india

**Comment by guinmoon** [comment]
Hi. I heve valid acc_id_practice and token_practice, i test it on curl -H "Authorization: Bearer 65977df04d32049a40a9b64cb802ca6a-*******" https://api-fxtrade.oanda.com/v3/accounts
and have response. But in secmaster_db_symbol_loader i have code 401 and {"errorMessage":"Insufficient authorization to perform request."}
As far as I understand 401 is a malformed request error.

**Comment by userLlamma** [comment]
I guess it works without this oanda cred, and this [oanda_cred.py] in the repo only stands for en example?
